#!/bin/bash

name=$1

if [ $# -lt 1  ]; then
    echo "Usage: $0 <Name> [user]"
    exit 1
fi

if [ -z $2 ]; then
    USER=root
else
    USER=$2
fi

read hostname key <<<$(./list-instances.rb | grep -w "\<$name" | awk '{print $4,$NF}')

if [ -z $hostname ]; then
    echo "$NAME: No such instance exists."
    exit 1
fi

keyfile="$PWD/$key.pem"

if [ ! -f "$keyfile" ]; then
    echo "Required SSH key file $keyfile does not exist."
    exit 1
fi

ssh -i $keyfile -o StrictHostKeyChecking=no $USER@$hostname
