#!/bin/bash

NAME=$1
KEY=$PWD/*.pem

if [ $# -lt 1  ]; then
    echo "Usage: $0 <Name> [user]"
    exit 1
fi

if [ -z $2 ]; then
    USER=root
else
    USER=$2
fi

hostname=$(./list-instances.rb | grep "$NAME" | awk '{print $4}')
if [ -z $hostname ]; then
    echo "$NAME: No such instance exists."
    exit 1
fi

ssh -i $KEY -o StrictHostKeyChecking=no $USER@$hostname
