#!/bin/bash

name=$1

if [ $# -lt 3  ]; then
    cat <<EOF
Usage:
 $0 <Name> SRC :DEST  - Copy local path SRC to remote path DEST
 $0 <Name> :SRC DEST  - Copy remote path SRC to local DEST
EOF
    exit 1
fi

first=$2
second=$3

read hostname key <<<$(./list-instances.rb | grep -w "\<$name" | awk '{print $4,$NF}')

if [ -z $hostname ]; then
    echo "$name: No such instance exists."
    exit 1
fi

keyfile="$PWD/$key.pem"

if [ ! -f "$keyfile" ]; then
    echo "Required SSH key file $keyfile does not exist."
    exit 1
fi

if [[ $first =~ ^:.* ]]; then
    scp -i $keyfile -o StrictHostKeyChecking=no -r root@$hostname:${first:1} $second
else
    scp -i $keyfile -o StrictHostKeyChecking=no -r $first root@$hostname:${second:1}
fi


