#!/bin/bash

NAME=$1
DST=$2

if [ $# -lt 2 ]; then
    echo "Usage: $0 <Name> <dst> [user]"
    exit 1
fi

if [ -z $3 ]; then
    USER=root
else
    USER=$3
fi

hostname=$(ec2-describe-instances --filter instance-state-name=pending,running,shutting-down,stopping,stopped --filter tag:"Owner=$EC2_OWNER" --filter tag:"Name=$NAME" | grep "^INSTANCE" | cut -f4)

scp -r -i $AWS_HOME/$EC2_SSH_KEY.pem -o StrictHostKeyChecking=no $USER@$hostname:$DST .
