#!/bin/bash

AMAZON_LINUX_AMI_OLD="ami-2272864b"
AMAZON_LINUX_AMI="ami-74f0061d"
GLUSTER_AMI="ami-5c8d7e35"

function create_instance()
# create_instance KEY OWNER NAME GROUP TYPE ZONE
{
    KEY=$1
    OWNER=$2
    NAME=$3

    GROUP=$4
    TYPE=$5
    ZONE=$6

    if [ -z $ZONE ]; then
        ZONECMD=""
    else
        ZONECMD="--availability-zone $ZONE"
    fi

    instance=$(ec2-run-instances $GLUSTER_AMI --key $KEY --instance-count 1 --group $GROUP --instance-type $TYPE  $ZONECMD| grep "^INSTANCE" | cut -f2)

    ec2-create-tags $instance --tag Owner="$OWNER" --tag Name="$NAME"

    echo "Instance $instance created."
}


function usage()
{
    echo "usage: $0 [-g <Group>] [-t <Instance Type>] [-a <Availability Zone>] -k <key> -o <Owner> <Name>"
    cat<<EOF
Defaults:
        <Group> = Gluster
        <Instance Type> = m1.large
EOF
}


function main()
{
    # defaults
    GROUP="Gluster"
    TYPE="m1.large"
    ZONE=""

    while getopts "ho:k:g:t:a:" OPT; do
        case "$OPT" in
            h)
                usage;
                exit 1
                ;;
            o)
                OWNER=$OPTARG
                ;;
            k)
                KEY=$OPTARG
                ;;
            g)
                GROUP=$OPTARG
                ;;
            t)
                TYPE=$OPTARG
                ;;
            a)
                ZONE=$OPTARG
                ;;
            \?)
                usage;
                exit 1
                ;;
        esac
    done

    shift $(($OPTIND - 1))

    if [ $# -ne 1 ]; then
        usage;
        exit 1
    fi

    NAME=$1

    if [ -z $KEY ] || [ -z $OWNER ]; then
        echo "Must specify key and owner"
        usage;
        exit 1;
    fi

    create_instance $KEY $OWNER $NAME $GROUP $TYPE $ZONE
}

main $*;