#!/bin/bash

# delete-volumes Server0
# Delete all volumes of the name "Server0-*"

if [ $# -lt 1 ]; then
    echo "usage: $0 <Name>"
    exit 1
fi

NAME=$1

volumes=$(ec2-describe-volumes --filter tag:"Owner=$EC2_OWNER" --filter tag:"Name=$NAME*"|grep "^VOLUME"|cut -f2)
for vol in $volumes
do
    ec2-delete-volume $vol
done
